name: DockerBuildPush
on:
  workflow_dispatch
jobs:
  Buildandpushdocker:
    runs-on: ubuntu-latest
    environment: DockerProd
    steps:
      - name: gitclone 
        run: git clone https://github.com/ArkoProvo531/Accenture_training.git
      - name: docker installation 
        run: curl -fsSL https://get.docker.com | sh 
      - name: docker login 
        run: docker login -u ${{secrets.DOCKERHUBUSERNAME}} -p ${{secrets.DOCKERHUBPASSWORD}}
      - name: current directory
        run: pwd && ls -la
      - name: docker build 
        run: cd Accenture_training && docker build . -t python-arkoapi:latest
      - name: test
        run: echo "hello"
      - name: docker tag & push  
        run: docker tag python-arkoapi:latest 1001arko/training123:latest && docker push 1001arko/training123:latest
        
      - name: login Target Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 40.71.56.99
          username: dockerpoc
          password: ${{ secrets.SERVERPASSWORD }}
          port: 22
          script: | 
             sudo docker login -u ${{secrets.DOCKERHUBUSERNAME}} -p ${{secrets.DOCKERHUBPASSWORD}}
             sudo docker pull 1001arko/training123:latest
             sudo docker run -d -P 1001arko/training123:latest
      
      
      
      
      
    
